renovate:
  image: 
    name: renovate/renovate
    entrypoint: [""]
  before_script:
    - cp config.js /usr/src/app/config.js
  script:
    - node /usr/src/app/dist/renovate.js $(cat repositories.txt | xargs)