renovate:
  variables:
    RENOVATE_TOKEN: $GITLAB_TOKEN
    GITHUB_COM_TOKEN: $GITHUB_TOKEN
  image:
    name: renovate/renovate
    entrypoint: ['']
  script:
    - ln -sF $CI_PROJECT_DIR/config.js /usr/src/app/
    - node /usr/src/app/dist/renovate.js
  only:
    - master
